### ISSUE TITLE
Exceed 64k bytes.

### ISSUE THREAD

**Issue by jongminkimkr** [HCL-TECH-SOFTWARE/domino-license-analysis-utility-DLAU#56] opened 2023-10-18 08:07 UTC
When run domino license analysis utility, "There was an Error in the (CheckLicenseTrackingSettings) function. The details of the Error are below: Error: Notes error: adding entry will cause text list to exceed 64K Entry not added. #: 4000  line #: 109" error occur.

**Comment by notesboy** [comment] 2024-11-08 20:24
This is a duplicate of https://github.com/HCL-TECH-SOFTWARE/domino-license-analysis-utility-DLAU/issues/32

**Closed** 2024-11-08 20:24 UTC
Labels: duplicate
