### ISSUE TITLE
Error in (GetDADirectories) funtion. Memory allocation exceeds 65.000 Bytes (#:315, line #: 113) in v1.2.2

### ISSUE THREAD

**Issue by ChristianHenseler** [HCL-TECH-SOFTWARE/domino-license-analysis-utility-DLAU#62] opened 2024-03-01 19:41 UTC
Using DLAU 1.2.2 with N12.0.2FP3.
While scanning the environment, DLAU stops with "There has been an error while running the analysis scans".
Looking into the scan log surfaces:
There was an Error in the (GetDADirectories) function. The details of the Error are below:
Error: Speicheranforderung über 65.000 Byte (#315, line #:113)

unable to continue DLAU scan

**Comment by OpenSourceTemplateDominoDev** [comment] 2024-03-01 19:44
@ChristianHenseler Please open a case with HCL so we can dig into your environmental data.

**Comment by notesboy** [comment] 2024-11-08 20:24
This is a duplicate of https://github.com/HCL-TECH-SOFTWARE/domino-license-analysis-utility-DLAU/issues/32

**Closed** 2024-11-08 20:25 UTC
Labels: duplicate
